### ISSUE TITLE
Latency

### ISSUE THREAD

**Issue by Suhail** [caoscott/SReC#2]
Hey, this is amazing and I can think of a bunch of different use-cases! What is the latency of getting to the lossless super-resolution version from the low-resolution version?

**Comment by caoscott** [comment]
By that do you mean latency of decompression? Measuring runtime on my GTX 1060, I get about 1.15 seconds/image for Open Image, which contains images of size > 512x512. In practice, we see that this runtime scales linearly with image height and width. A detailed breakdown of runtime by each scale of super-resolution and for different scales is on page 11 of our paper: https://arxiv.org/pdf/2004.02872.pdf
I can probably give more advice on latency if you can tell me your use cases.
