### ISSUE TITLE
Testing SReC with anime images

### ISSUE THREAD

**Issue by DonaldTsang** [caoscott/SReC#5]
Would it be good to test this out with https://www.gwern.net/Danbooru2019 and see if there will be performance differences if the images have certain properties?

For reference:
- ImageNet has ~14M http://image-net.org/about-stats
- Places has ~10M http://places2.csail.mit.edu/
- OpenImages has ~9M https://storage.googleapis.com/openimages/web/factsfigures.html
- Danbooru has ~4M (which is the largest drawing related dataset)
- Objects365 has ~2M https://www.objects365.org/overview.html

**Comment by DonaldTsang** [comment]
Just as a side reference:
- Places has ~10M http://places2.csail.mit.edu/ and
- Objects365 has ~2M https://www.objects365.org/overview.html

**Comment by DonaldTsang** [comment]
Some other dataset browsers:
- https://www.datasetlist.com/
- http://homepages.inf.ed.ac.uk/rbf/CVonline/Imagedbase.htm

**Comment by caoscott** [comment]
Unfortunately I don't have the time to support this currently. Since our model weights are public, I encourage you to try it yourself. I would begin with the starter steps in our README and replace Open Images dataset with your custom dataset. Let me know if you have any question.

**Comment by DonaldTsang** [comment]
For those that are interested https://github.com/caoscott/SReC/issues/6
