### ISSUE TITLE
Comparison of performance between SReC and other "highly compressed formats"

### ISSUE THREAD

**Issue by DonaldTsang** [caoscott/SReC#6]
Please take a look at https://docs.google.com/spreadsheets/d/1ju4q1WkaXT7WoxZINmQpf4ElgMD2VMlqeDN2DuZ6yJ8/edit
Google and FLIF has recently published a new image format, JPEG-XL, as a replacement to PNG.
Others have also made similar formats, namely AVIF, HEIF, WebP and BPG.

It might be fun to test out the compression ratio and time of SReC in comparison to others.
However is that it should use "clean" PNG instead of JPEG since JXL is strong for preserving artifacts.

**Comment by caoscott** [comment]
I think this is interesting but unfortunately I don't have the time to support this at the moment. I would encourage you to try it yourself on the Open Images test set. The test set Images should already be cleaned of JPEG artifacts.
